[line_break]
disabled = false


# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[Î»](green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[â¯](fg:124) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 8
style = "fg:75"

[cmd_duration]
style = "fg:yellow"

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[elixir]
symbol = "ğŸ”® "

[git_branch]
style = "fg:221"
[git_metrics]
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
[git_status]

[status]
style = "fg:124"
symbol = "ğŸ”´"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = false
disabled = false
